import unittest
from context_engine import ContextEngine
import knowledge_agent


class TestContextEngine(unittest.TestCase):

    def test_extract_pr_references(self):
        text = "Modernize the authentication UI. Referencing closed PR #143 and merged PR #151 for details. Also check pull/160."
        refs = ContextEngine.extract_pr_references(text, current_issue_number=142)
        self.assertEqual(refs, [143, 151, 160])

    def test_extract_pr_references_excludes_current_issue(self):
        text = "Fixes bug in issue #142. See also #143."
        refs = ContextEngine.extract_pr_references(text, current_issue_number=142)
        self.assertEqual(refs, [143])

    def test_categorize_comments(self):
        comments = [
            {"user": {"login": "Maintainer"}, "body": "Don't modify the OAuth flow."},
            {"user": {"login": "Contributor"}, "body": "The UI is actually generated by AuthPanel."},
            {"user": {"login": "Contributor"}, "body": "@Knowledge How should I start?"}
        ]
        directives, discussions = ContextEngine.categorize_comments(comments, issue_author="Maintainer")
        
        self.assertTrue(any("OAuth flow" in d["body"] for d in directives))
        self.assertTrue(any("AuthPanel" in d["body"] for d in discussions))

    def test_build_structured_context_demo(self):
        issue = {
            "number": 142,
            "title": "Modernize authentication UI",
            "body": "Modernize auth UI using AuthPanel. See PR #143 and PR #151.",
            "user": {"login": "Maintainer"}
        }
        comments = [
            {"user": {"login": "Maintainer"}, "body": "Don't modify the OAuth flow."},
            {"user": {"login": "Contributor"}, "body": "The UI is actually generated by AuthPanel."}
        ]
        
        ctx = ContextEngine.build_structured_context(
            access_token=None,
            owner="demo",
            repo="demo-repo",
            issue=issue,
            comments=comments,
            fetched_files={"KNOWLEDGE.md": "Rule 1: Be helpful."}
        )

        self.assertEqual(ctx["issue_number"], 142)
        self.assertEqual(len(ctx["linked_prs"]), 2)
        self.assertEqual(ctx["linked_prs"][0]["number"], 143)
        self.assertEqual(ctx["linked_prs"][1]["number"], 151)
        self.assertTrue(any("OAuth flow" in d["body"] for d in ctx["maintainer_directives"]))
        self.assertIn("=== SURROUNDING HISTORICAL CONTEXT: LINKED PULL REQUESTS ===", ctx["formatted_evidence"])

    def test_generate_knowledge_answer_handoff(self):
        issue = {
            "number": 142,
            "title": "Modernize authentication UI",
            "body": "Modernize auth UI using AuthPanel. See PR #143 and PR #151.",
            "user": {"login": "Maintainer"}
        }
        comments = [
            {"user": {"login": "Maintainer"}, "body": "Don't modify the OAuth flow."},
            {"user": {"login": "Contributor"}, "body": "The UI is actually generated by AuthPanel."}
        ]

        result = knowledge_agent.generate_knowledge_answer(
            access_token="",
            owner="demo",
            repo="demo-repo",
            issue=issue,
            comments=comments,
            custom_query="@Knowledge How should I start?"
        )

        self.assertIn("answer", result)
        self.assertIn("structured_context", result)
        self.assertTrue(
            "Engineering Handoff" in answer or "Before Starting" in answer or "Overview" in answer or "Constraints" in answer
        )
        self.assertIn("OAuth flow", answer)
        self.assertIn("143", answer)
        self.assertIn("151", answer)



if __name__ == "__main__":
    unittest.main()
